---
title: "Simulation"
author: "Lianghui Li"
date: "10/8/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(reshape2)
library(ggplot2)
```


```{r}
#given parameters
k0 = 0.05
l0 = 1
sigma = 0.15
n = 0.02
delta = 0.03

```


The expression that we use to define steady state, we define as the 'difference' in belows $\dot{k} = \sigma f(k)+ (n+ \delta)k$

```{r}
#construct table

#create function calculating wanted result under steady state assuption 
dif.cal = function(alpha){
k = numeric()
l = numeric()
k[1] = k0
l[1] = l0
i = 1
dif = numeric()
dif[1] = 1

#the difference is the loop stop standard, where the difference defined in the note should 
#be 0, but what we want is just to show the convergency not the exact 0
while(!any(dif < 0.00000001)) {
capital = k[i]
labor = l[i]
#update difference, labor and capital for each year
dif[i+1] = sigma*(capital/labor)^alpha - (n+delta)*capital/labor
k[i+1] = k[i] + sigma*(k[i])^(alpha) *(l[i])^(1-alpha) - delta*k[i]
l[i+1] = (1+n)^(i+1)
i = i + 1
}
return(dif)
}

#when alpha = 0.33
dif1 = dif.cal(0.33)[-1]
df1 = data.frame(s = seq_along(dif1[1:500]), dif1[1:500])
colnames(df1) = c('x', 'y')

#when alpha = 0.67
dif2 = dif.cal(0.67)[-1]
df2 = data.frame(s = seq_along(dif2[1:500]), dif2[1:500])
colnames(df2) = c('x', 'z')

#create data frame with long format
df.tot = left_join(df1, df2)

df.long = melt(df.tot, id.vars = 'x')
df.long$variable = c(rep('0.33', 500), rep('0.67', 500))

#create plot(time series)
ggplot(df.long, aes(x = x, y = value, col = variable)) +
  geom_line(linetype = "dotdash") + 
  labs(x = 'Time', y = expression(paste(sigma,
                              'f(k)', "+", "(n+", delta, ')','k', sep = "")), 
       col = expression(alpha), title = "Steady State Simulation") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

```

It's clear that with greater $\alpha$, it will take longer to get to steady state based on the assumption.